version: '3.8'

services:
  bookify-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./bookify_db.sqlite:/usr/src/data
    environment:
      - NODE_ENV=production