name: Build & Test

on:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.json'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**/*.md'
      - '**/*.json'

env:
  NODE_VERSION: '20.x'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: 🗑️ Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: 'development'
          onlyRemoveDeployments: true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Create .env file for server
        run: |
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> ./server/.env
          echo "OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}" >> ./server/.env
          echo "OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}" >> ./server/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./server/.env

      - name: Create .env file for client
        run: |
          echo "VITE_APP_TITLE=${{ secrets.VITE_APP_TITLE }}" >> ./client/.env
          echo "VITE_APP_SLOGAN=${{ secrets.VITE_APP_SLOGAN }}" >> ./client/.env
          echo "VITE_BACKEND_ENDPOINT=${{ secrets.VITE_BACKEND_ENDPOINT }}" >> ./client/.env
          echo "VITE_ENVIRONMENT=${{ secrets.VITE_ENVIRONMENT }}" >> ./client/.env
          echo "VITE_MOCK_CALENDER=${{ secrets.VITE_MOCK_CALENDER }}" >> ./client/.env

      - name: Install dependencies using npm workspaces
        run: npm install

      - name: Build all dependencies
        run: npm run build